import { COMMENT_MAX_LENGTH } from './length.js';

export const SuccessResponses = {
    LOGIN_SUCCESS: 'Zalogowano pomyślnie.',
    LOGOUT_SUCCESS: 'Wylogowano pomyślnie.',
    TERMS_CHANGED_SUCCESS: 'Dane komunikatu zostały zaktualizowane.',
    PUBLICATION_COMMENT_DELETE_SUCCESS: 'Komentarz do publikacji został usunięty.',
    PUBLICATION_COMMENT_CREATE_SUCCESS: 'Komentarz został utworzony.',
    USER_CREATE_SUCCESS: 'Użytkownik został utworzony.',
    USER_UPDATE_SUCCESS: 'Użytkownik został zaktualizowany.',
    USERS_UPDATE_SUCCESS: 'Użytkownicy zostali zaktualizowani.',
    BIRTHDAY_NONE: 'Dzisiaj nikt nie świętuje.',
    PUBLICATION_DELETE_SUCCESS: 'Publikacja została usunięta.',
    PUBLICATION_CREATE_SUCCESS: 'Publikacja została utworzona.',
    PUBLICATION_ARCHIVE_SUCCESS: 'Publikacja została zarchiwizowana.',
    PUBLICATION_RESTORE_SUCCESS: 'Publikacja została przywrócona.',
    PUBLICATION_SAVE_SUCCESS: 'Zapisano pomyślnie.',
    PUBLICATION_STATUS_CHANGE_SUCCESS: 'Status publikacji został zaktualizowany.',
};
export const FailedResponses = {
    LOGIN_FAILED: 'Nieprawidłowy login lub hasło!',
    LOGOUT_FAILED: 'Niepoprawny token.',
    TERMS_REJECTED: 'Nie zaakceptowano regulaminu.',
    USER_IS_BLOCKED: 'Ten użytkownik jest zablokowany!',
    SERVER_ERROR: 'Wystąpił błąd, spróbuj ponownie później.',
    ROLE_NOT_FOUND: 'Nie znaleziono takiej roli.',
    DONT_HAVE_PERMISSIONS: 'Nie masz takich uprawnień.',
    PUBLICATION_TYPE_NOT_FOUND: 'Nie znaleziono takiego typu.',
    PUBLICATION_STATE_NOT_FOUND: 'Nie znaleziono takiego stanu.',
    PUBLICATION_COMMENT_NOT_FOUND: 'Nie znaleziono takiego komentarza do publikacji.',
    PUBLICATION_COMMENT_DELETE_NOT_AUTHOR: 'Nie możesz usunąć czyjegoś komentarza.',
    PUBLICATION_COMMENT_EMPTY: 'Komentarz nie może być pusty.',
    PUBLICATION_COMMENT_LENGTH: `Komentarz nie może przekroczyć ${COMMENT_MAX_LENGTH} znaków.`,
    PUBLICATION_COMMENT_PUBLICATION_NOT_FOUND: 'Brak ID publikacji, której dodawany komentarz dotyczy.',
    PUBLICATION_NOT_FOUND: 'Nie znaleziono takiej publikacji.',
    PUBLICATION_LENGTH: 'Przekroczono limit znkaów. Zmiany nie zostały zapisane.',
    PUBLICATION_TITLE_LENGTH: 'Przekroczono limit znaków (255) dla tytułu. Zmiany nie zostały zapisane.',
    PUBLICATION_NOT_SELECTED_ROUTE: 'Publikacja nie ma ustawionej ścieżki głównej. Nie można wykonać operacji opublikowania.',
    INPUTS_ARE_EMPTY: 'Wypełnij wszystkie wymagane pola',
    USER_NOT_FOUND: 'Nie znaleziono użytkownika.',
};